### PR TITLE
Changes needed to target Android 14

### PR DESCRIPTION
**Pull request by Xavron**
All changes to get the app working with a target of Android 14.

I did not look into the following enough to know if they are indeed the best choice? Data seems like it should be. Exported didn't double check and just plugged that into there.

~Data or other? _(edit: d'oh! Just seen the note that DATA_SYNC is to be deprecated in the future. It isn't yet lol.)_
FOREGROUND_SERVICE_TYPE_DATA_SYNC
foregroundServiceType="dataSync"~ *dealt with in commit b2e6e0e477c267454b2881c951a1b15b63fa0ca8 due to DATA_SYNC nearing deprecated status.

Exported or not?
RECEIVER_EXPORTED *see below https://github.com/ppareit/swiftp/pull/210#issuecomment-1878798610

### CODE REVIEW

**Comment by Xavron** [comment]
Found more that show up later. Need to add more fixes.

**Comment by Xavron** [comment]
RECEIVER_NOT_EXPORTED does seem to be working just fine. Am currently not seeing any reason to need RECEIVER_EXPORTED.

**Comment by Xavron** [comment]
Issue seen. Major performance loss when app is in the background. Will look into it further.

The device has no battery/power saver enabled and the app is given full unrestricted use (adaptive battery is the only thing enabled but was enabled in A13 and does it when plugged in as well). Am thinking its probably related to A14's new changes so will need to look into if anything can affect it differently.

	All other conditions same
	2,706 files; 710 folder; size 54.9MB

	screen on and app open...
		total time: 7m 37s

	anything else...
		total time: 19m 51s

And indeed, tests I've run that should take approx 58 minutes can take up to 3 hours making it 3x slower.

This affects everything from transfer up and down to deletions.

To speed it up: The device display must be _on_ and the app must be _visible_. Browsing away from the app or having the app open with the display off will drop the speed.

**Comment by Xavron** [comment]
Should be good. Been using it for some weeks now :)

**Comment by Xavron** [comment]
So far I can't figure out what happened. But after the March Android security update (coincidence?) the wake locks just don't appear to work anymore even adjusted fully to Android 14, using old, etc. I checked and it even only shows 1% battery with lots of transfer time.

It almost seems like Android 14 battery stats or wake locks are now broken. I will probably need to look into Android logcat entries. What a pain.

Still works fine that I don't consider it a problem (to me it isn't but its a thing and so to someone else I'm sure it would be something).

**Comment by Xavron** [comment]
July update on this.

No negative has been seen from target of Android 14 on any OS version.

Android 14 itself however - regardless of target - on longer transfers will occasionally sleep the background app. This can cause disconnects or failures from clients will too short of a timeout during times when Android 14 forces it into sleep.

Workarounds are to increase client timeout or it can also be done with setting full wake locks in the app along with keeping the screen on).

Is there a better way around this that can be done in code? I've not found anything. Android 14 is designed to be very aggressive at attempts to save battery by micro managing and forcing apps.

I do think some Android 14 update made it worse. Battery stats still aren't working as they should. They will have also worked on various battery stuff in later updates since release as well.

Ultimately, Android 14 works. I've used it fine enough for a few months now.

**Comment by ppareit** [comment]
You probably introduced FLAG_KEEP_SCREEN_ON to solve the slowdowns here.

**Pull request merged**
